encode url for following sub
OpenCollar/opencollar pull request #1009
Opened 2017-02-06 20:18 UTC by Mace68

Encodes the location section of the follow slurl to fix a problem with spaces in sim names.

relates to issue #1008

2017-02-07 11:11 UTC, WendyStarfall requested changes
To make this fully work, we can't escape the sPos string! 🙊 

``llOwnerSay("Follow your Partner(s) right way by clicking here: secondlife:///app/teleport/"+llEscapeURL(g_sRegion)+sPos);``

2017-02-07 14:54 UTC, WendyStarfall approved these changes

2017-02-07 14:54 UTC, merged

2017-02-07 23:41 UTC, Mace68 commented
Awesome. Should I delete this branch like it says or keep it?

2017-02-08 15:02 UTC, WendyStarfall commented
You can delete it, it's already merged!