Particles in titler
OpenCollar/opencollar pull request #1050
Opened 2017-09-20 02:33 UTC by manonev

Needs a new prim with appropriate desc (and should degrade gracefully in its absence).  Not hooked into menu system yet; has to be done with # title particle <KEY>.  And that's another thing it doesn't have yet: shorthand names for some standard particles (I've made and found a few; someone with better graphic skills could do good things).

This is cooler than it sounds: the particles are not flying around; they're stationary graphics hanging in the air.  So they could be words like hovertext, but with cool graphics and coloring and design and everything.  One notable issue: since the particles have to be *at* a prim, there has to be a prim overhead for them, which means a prim linked to but fairly far from the collar, so it moves pretty widely with small movements of the head.

See what you think,

2017-09-20 02:42 UTC, WendyStarfall commented
I like it and thanks for the contribution. There is a withering concept called ``titler++`` somewhere on my graveyard on bitbucket that also uses particles over classic hovertext that was never finished. We will have to see how it works out with client-side lag and use the regular FloatText element, which should be no big deal.

2017-09-30 09:43 UTC, GarvinTwine commented
Sorry I didnt get to reply to this earlier. 
I like the idea and it could be added.

I see the main challenge here to enable and allow the users to add their own textures, else it will be a nice feature but with only prepared few textures to use.

As this is really just in the first developing stages, I would suggest to continue in an own branch before we start merging into this one.

2017-09-30 09:53 UTC, GarvinTwine requested changes
I see no reason why not using the already existing FloatTextPrim for this, as long as only one of the features can be used, either float text or particles, there should be no conflict at all, where having to add a new prim will make this only work for new collars and not in hundred thousands already out there.

2017-10-01 01:50 UTC, manonev commented
I've been working on this some, and have gotten it to a point more worth considering.  I have a small collection of textures in a menu, as well as the option to paste a texture UUID into a textbox, but yes, it really should be something you can add to a little more easily than pasting UUIDs.

I'll do some testing; probably should be possible to drop textures into the collar and use those, perhaps with a prefix or something in case there are other textures for other purposes.  Possible downside to that is proliferation of copies of the "standard" ones, if they're distributed with the collars.  Or maybe some standard ones with UUIDs hardcoded, plus textures dropped in, etc...

I was using a separate prim because I wasn't thinking that we necessarily should allow only one at a time, but perhaps it would be okay.  Or maybe even better, maybe I could make it smart enough to use a dedicated prim IF one was available...

I'll see if I can do some/all of these things, and push my branch soon so you can see what you think.  Thanks for looking!

2017-11-30 16:41 UTC, WendyStarfall commented
This would be a perfectly fine, new plugin too by the way.

2017-12-14 11:55 UTC, closed without merging