Perform an additional operation on safewords to trim spaces
OpenCollar/opencollar pull request #971
Opened 2016-10-01 09:30 UTC by stawberri

Back when my safeword actually did something, I noticed that pressing alt+enter on Firestorm produced a message like `(( SAFEWORD ))` while OpenCollar expected a message like `((SAFEWORD))`. This seemed rather inconvenient in a situation that would merit needing to use a safeword.

My implementation converts the wearer's message into a list and and then pulls the first element from it only if the list is one element long. This works out because the safeword setting command does a similar thing where it pulls only one word from the message.

Now that I think about it, parsing every message someone sends sounds like a lot of overhead, so if you like this idea, I could look into adding an extra check if the first or last character of the string at that point is a space. If neither is a space, then this whole list thing is completely unnecessary. 😄

2016-10-01 11:59 UTC, GarvinTwine requested changes
Nice catch, though i think Firestorm should change their OOC as they show it without spaces in the Preference-Window ;).
But LSL has nice function to Trim Spaces:
llTrimString(string,TRIM_STRING); that added to the if condition where the "(())" are found and all should be fine, the /me case is already handled anyway above that.

2016-10-01 22:59 UTC, stawberri commented
Okay, I did that and tested it. It works!

My `/me` case _isn't_ actually handled though, because my example had multiple spaces in it (like `/me    SAFEWORD`). I have less of a rationale for needing to support that though. 😅

2016-10-02 10:26 UTC, WendyStarfall approved these changes
Tested and works well!

2016-10-02 10:27 UTC, GarvinTwine approved these changes

2016-10-02 10:46 UTC, merged

2016-10-02 10:54 UTC, WendyStarfall commented
#974