check on rez for other installers
OpenCollar/opencollar pull request #975
Opened 2016-10-02 14:13 UTC by GarvinTwine

and dont allow installations to initiate when one is found.
#970

2016-10-02 17:11 UTC, WendyStarfall requested changes
I've played around a bit in-world and thought that we maybe should use a notify function, similar to as we already do in other devices. Right now our installers all have very long names. Something like:

``` LSL
Notify(key g_kUser, string sMsg) {
    llSetObjectName("Installer");
    llRegionSayTo(g_kUser,0,sMsg);
    llSetObjectName(g_sObjectName);
}
```

We can also consider to lend the user a hand and print a SLURL to where the other installer is hiding. I've messed with that too but only had this dorky function:

``` LSL
string GetSLURL() {
    string sMaps="http://maps.secondlife.com/secondlife";
    string sRegion=llGetRegionName();
    vector vLocal=llGetLocalPos();
    string sX=(string)llRound(vLocal.x);
    string sY=(string)llRound(vLocal.y);
    string sZ=(string)llRound(vLocal.z);
    return (sMaps+"/"+llEscapeURL(sRegion)+"/"+sX+"/"+sY+"/"+sZ);
}
```

Maybe it's better to just do a NameURI for the other installer device. Those hyperlinks display world coordinates with `/inspect` anyway. Helping the user to find hidden installers might be important if we take the highlander solution. In a worst case, the user fails to find the other installer and gets very frustrated. 🙊

2016-10-03 02:55 UTC, GarvinTwine commented
I will name it Say(string) as this goes only to the owner anyway and so differs from our Notify function.
There's from the way of going it no real difference if printing out a URI or map as both need the same formatted SURL (for objects this differs from agents).

2016-10-03 09:45 UTC, WendyStarfall approved these changes

2016-10-03 10:16 UTC, merged

2016-10-13 00:17 UTC, WendyStarfall commented
#982